console.log('')
console.log('The setup script has moved to a separate CLI package.')
console.log('Use: npx @jon8800/create-payload-starter')
console.log('')
console.log('See: https://github.com/jon8800/payload-toolkit')
console.log('')
process.exit(0)
